#!/usr/bin/env python3
"""
Conversation practice for LinguaDaily — speaking + listening.

The user starts a short spoken conversation with /convo.  Each turn:
  1. The bot sends a TTS audio line (the "partner"), plus the line text
     and its translation, both hidden behind Telegram spoilers.
  2. The user records a voice-message reply.
  3. The reply is transcribed (STT endpoint — see src/stt.py) and scored;
     the partner's next line is generated by an LLM (ideally a small,
     fast model — configure via llm.task_models.convo or a per-profile
     llm_convo_model override).

The conversation topic is the profile's latest delivered lesson, and the
language level follows the profile's CEFR target_level.

Config (config.json):
    "stt": {"base_url": "...", "model": "..."}   # required for /convo
    "llm": {"task_models": {"convo": "small-model"}}  # optional
    "convo": {"turns": 4}                        # optional default turns

Usage (import):
    from src.convo import ConvoHandler
    handler = ConvoHandler(config, telegram_bot_instance)
    await handler.start_convo(chat_id, profile_name)
    await handler.handle_voice(message)
"""

import asyncio
import html
import logging
import os
import time
from typing import Optional

from config import (
    CONVO_DEFAULT_TURNS,
    CONVO_MAX_TURNS,
    CONVO_MIN_TURNS,
    CONVO_SESSION_TIMEOUT_SECS,
    DEFAULT_LEARNING_LANGUAGE,
    DEFAULT_NATIVE_LANGUAGE,
    OUTPUT_DIR,
    TTS_DEFAULT_VOICE,
    resolve_language_name,
    tts_speed_for_level,
)
from stt import is_configured, transcribe, voice_to_wav

logger = logging.getLogger(__name__)


# ── Prompts ─────────────────────────────────────────────────────────

CONVO_OPEN_SYSTEM = """You are a friendly conversation partner for a {level} learner of {language_name}.

The conversation is about the learner's daily article: "{topic}".

Rules:
- Write ONE natural opening line or question in {language_name} about the topic.
- 1-2 short sentences, simple {level}-level vocabulary.
- "translation": the line translated into {native_lang}.

Respond with ONLY a JSON object:
{{"reply": "...", "translation": "..."}}"""

CONVO_NEXT_SYSTEM = """You are a friendly conversation partner for a {level} learner of {language_name}.

The conversation is about the learner's daily article: "{topic}".
The learner answers by SPEAKING; their utterance was transcribed by speech
recognition and may contain recognition errors.

{history}The learner just said: "{user_speech}"

Respond with ONLY a JSON object:
- "feedback": brief feedback in {native_lang}, max 2 sentences. Note the most
  important language error if there is one; otherwise confirm it was fine.
  Concise and factual — no praise padding.
- "score": integer 0-100 for grammar and word choice. Fair scale:
  85-100 correct and natural · 60-84 understandable, minor errors ·
  40-59 significant errors · below 40 mostly wrong.
- "reply": your next line in {language_name} — a natural response to what they
  said, 1-2 short sentences, simple {level}-level vocabulary, keep it going.
- "translation": the reply translated into {native_lang}."""


def _level_label(level: str) -> str:
    """CEFR level for prompts — 'original' becomes a plain description."""
    lvl = (level or "original").upper()
    if lvl in ("A1", "A2", "B1", "B2", "C1", "C2"):
        return lvl
    return "A2-B1 (simple)"


def _clamp_turns(turns: Optional[int]) -> int:
    if not turns:
        return CONVO_DEFAULT_TURNS
    return max(CONVO_MIN_TURNS, min(CONVO_MAX_TURNS, int(turns)))


# ── Handler ─────────────────────────────────────────────────────────

class ConvoHandler:
    """Manages short spoken conversation sessions inside Telegram.

    Session state lives in self._sessions[chat_id]; the Telegram bot
    routes /convo and voice messages here (see telegram_bot.py).
    """

    def __init__(self, config: dict, telegram_bot):
        self.config = config
        self.bot = telegram_bot
        self._sessions: dict[int, dict] = {}
        self._llama_client = None

    # ── Session lifecycle ─────────────────────────────────────────

    def _get_session(self, chat_id: int) -> Optional[dict]:
        """Return the active session or None if expired/missing."""
        session = self._sessions.get(chat_id)
        if not session:
            return None
        if time.time() - session["created_at"] > CONVO_SESSION_TIMEOUT_SECS:
            del self._sessions[chat_id]
            return None
        # Refresh the inactivity timeout
        session["created_at"] = time.time()
        return session

    def _end_session(self, chat_id: int):
        self._sessions.pop(chat_id, None)

    def _get_llama_client(self, profile_name: str):
        if (self._llama_client is None
                or self._llama_client.profile_name != profile_name):
            from llama_client import LlamaClient
            self._llama_client = LlamaClient(
                config=self.config, profile_name=profile_name
            )
        return self._llama_client

    # ── Public API ────────────────────────────────────────────────

    async def start_convo(self, chat_id: int, profile_name: str,
                          turns: Optional[int] = None):
        """Start a conversation session for the profile's latest lesson."""
        # Pick up config changes made through the web UI
        self.config = self.bot.config or self.config
        self._end_session(chat_id)

        profile = self.config.get("profiles", {}).get(profile_name, {})
        lang_code = profile.get("learning_language", DEFAULT_LEARNING_LANGUAGE)
        native = profile.get("native_language", DEFAULT_NATIVE_LANGUAGE)
        level = profile.get("target_level", "original")

        # ── Prerequisites ─────────────────────────────────────────
        if not is_configured(self.config):
            await self._send(
                chat_id,
                "⚠️ Speech-to-text is not configured.\n"
                "Add an <code>stt</code> section to config.json "
                "(base_url + model) and restart.",
            )
            return
        if not profile.get("use_tts", True) or not self.config.get("tts"):
            await self._send(
                chat_id,
                "⚠️ TTS is disabled for this profile — "
                "conversation practice needs audio.",
            )
            return

        client = self._get_llama_client(profile_name)
        if not client.resolve_model("convo"):
            await self._send(
                chat_id,
                "⚠️ No LLM model configured — set <code>llm.default_model</code> "
                "(optionally a small fast one via <code>llm.task_models.convo</code>).",
            )
            return

        lesson = None
        try:
            lesson = self.bot.db.get_latest_lesson(profile_name)
        except Exception as e:
            logger.error("Could not fetch latest lesson: %s", e)
        if not lesson or not (lesson.get("title") or "").strip():
            await self._send(
                chat_id,
                "⚠️ No lesson yet — run /another first, then try /convo.",
            )
            return

        if not turns:
            turns = (self.config.get("convo", {}) or {}).get("turns")
        turns = _clamp_turns(turns)
        placeholder = await self._send(
            chat_id, "🎧 Preparing your conversation…")

        # ── Opening line (LLM) ────────────────────────────────────
        data = await asyncio.to_thread(
            self._generate_opening, client, lesson, lang_code, native, level)
        if not data or not str(data.get("reply", "")).strip():
            await self._delete(placeholder)
            await self._send(
                chat_id,
                "⚠️ Could not start the conversation — LLM unavailable. "
                "Try again.",
            )
            return
        reply = str(data["reply"]).strip()[:300]
        translation = str(data.get("translation", "")).strip()[:300]

        session = {
            "mode": "convo",
            "profile": profile_name,
            "turns_total": turns,
            "topic": lesson.get("title", ""),
            "level": level,
            "lang_code": lang_code,
            "native_lang": native,
            "lines": [],          # [{"transcript": str, "score": int}, …]
            "created_at": time.time(),
            "busy": False,
        }
        self._sessions[chat_id] = session

        # ── Audio (TTS) ───────────────────────────────────────────
        wav = await asyncio.to_thread(
            self._synth_line, profile_name, reply, lang_code, level)

        await self._delete(placeholder)
        if wav:
            await self._send_audio(
                chat_id, wav,
                self._turn_caption(session, 1, reply, translation))
        else:
            await self._send(
                chat_id,
                "(⚠️ TTS failed — text only)\n"
                + self._turn_caption(session, 1, reply, translation))
        logger.info("Convo started for chat %d (profile '%s', %d turns, "
                    "topic: %s)", chat_id, profile_name, turns,
                    session["topic"])

    async def handle_voice(self, message):
        """Handle a voice message — the user's spoken answer."""
        chat_id = message.chat.id
        session = self._get_session(chat_id)
        if not session:
            await self._send(
                chat_id,
                "No active conversation — start one with /convo.",
            )
            return
        if session.get("busy"):
            await self._send(
                chat_id,
                "⏳ Still working on the last answer — one moment.",
            )
            return

        session["busy"] = True
        placeholder = await self._send(chat_id, "🎧 Transcribing…")
        try:
            await self._process_voice(message, session, chat_id)
        except Exception as e:
            logger.error("Convo voice processing failed: %s", e, exc_info=True)
            await self._send(
                chat_id,
                "⚠️ Something went wrong — try recording again.",
            )
        finally:
            session["busy"] = False
            await self._delete(placeholder)

    # ── Voice pipeline ────────────────────────────────────────────

    async def _process_voice(self, message, session: dict, chat_id: int):
        """Download → convert → transcribe → score → next line."""
        profile = session["profile"]
        lang_code = session["lang_code"]

        # 1) Download the Telegram voice note (OGG/Opus)
        bot = await self.bot._get_aiogram_bot()
        work_dir = os.path.join(str(OUTPUT_DIR), profile, "convo")
        os.makedirs(work_dir, exist_ok=True)
        ogg_path = os.path.join(work_dir, f"voice_{int(time.time() * 1000)}.ogg")
        try:
            # bot.download() accepts the Voice object directly (it reads file_id)
            await bot.download(message.voice, destination=ogg_path)
        except Exception as e:
            logger.error("Could not download voice message: %s", e)
            await self._send(chat_id, "⚠️ Could not download your voice message.")
            return

        # 2) Convert to WAV (ffmpeg)
        wav_path = await asyncio.to_thread(voice_to_wav, ogg_path, work_dir)
        if not wav_path:
            await self._send(
                chat_id,
                "⚠️ Could not process the audio — is ffmpeg installed on the daemon?",
            )
            return

        # 3) Transcribe (STT endpoint)
        transcript = await asyncio.to_thread(
            transcribe, wav_path, lang_code, self.config)
        self._cleanup(work_dir, ogg_path, wav_path)

        if transcript is None:
            await self._send(
                chat_id,
                "⚠️ Transcription failed — is the STT endpoint up? Try again.",
            )
            return
        if not transcript:
            await self._send(
                chat_id,
                "🤔 I couldn't catch anything — try again?",
            )
            return

        # 4) Score + next line (LLM)
        client = self._get_llama_client(profile)
        data = await asyncio.to_thread(
            self._generate_next, client, session, transcript)
        if not data or not str(data.get("reply", "")).strip():
            await self._send(
                chat_id,
                "⚠️ The tutor is unavailable — try recording again.",
            )
            return

        score = max(0, min(100, int(data.get("score", 0) or 0)))
        feedback = str(data.get("feedback", "")).strip()[:500]
        reply = str(data["reply"]).strip()[:300]
        translation = str(data.get("translation", "")).strip()[:300]

        session["lines"].append({"transcript": transcript, "score": score})
        turn_no = len(session["lines"])
        total = session["turns_total"]

        # 5) Feedback message
        fb_lines = [
            f"✅ <b>Turn {turn_no}/{total}</b> · score: <b>{score}/100</b>",
            f"💬 <i>“{html.escape(transcript)}”</i>",
        ]
        if feedback:
            fb_lines += ["", html.escape(feedback)]
        await self._send(chat_id, "\n".join(fb_lines))

        # 6) Summary or next line
        if turn_no >= total:
            await self._send_summary(chat_id, session)
            self._end_session(chat_id)
            return

        wav = await asyncio.to_thread(
            self._synth_line, profile, reply, lang_code, session["level"])
        if wav:
            await self._send_audio(
                chat_id, wav,
                self._turn_caption(session, turn_no + 1, reply, translation))
        else:
            await self._send(
                chat_id,
                "(⚠️ TTS failed — text only)\n"
                + self._turn_caption(session, turn_no + 1, reply, translation))

    async def _send_summary(self, chat_id: int, session: dict):
        scores = [l["score"] for l in session["lines"]]
        avg = round(sum(scores) / len(scores)) if scores else 0
        lines = [
            "🏁 <b>Conversation complete!</b>",
            f"Topic: <i>{html.escape(session['topic'])}</i>",
            f"Average score: <b>{avg}/100</b>",
            "",
        ]
        for i, l in enumerate(session["lines"], 1):
            lines.append(
                f"{i}. <i>“{html.escape(l['transcript'])}”</i> — {l['score']}/100")
        lines += ["", "<i>(Scores are based on the transcribed words.)</i>"]
        await self._send(chat_id, "\n".join(lines))

    # ── LLM calls ─────────────────────────────────────────────────

    def _generate_opening(self, client, lesson: dict, lang_code: str,
                          native: str, level: str) -> Optional[dict]:
        system = CONVO_OPEN_SYSTEM.format(
            level=_level_label(level),
            language_name=resolve_language_name(lang_code),
            topic=(lesson.get("title") or "today's article")[:200],
            native_lang=resolve_language_name(native),
        )
        return client.chat_json(
            system, "Start the conversation.", task="convo")

    def _generate_next(self, client, session: dict,
                       transcript: str) -> Optional[dict]:
        # Compact history of previous exchanges (keeps the call small)
        lines = session.get("lines", [])
        history = ""
        if lines:
            prev = lines[-1]
            history = (
                f"Conversation so far:\nLearner: \"{prev['transcript']}\"\n\n"
            )
        system = CONVO_NEXT_SYSTEM.format(
            level=_level_label(session["level"]),
            language_name=resolve_language_name(session["lang_code"]),
            topic=(session.get("topic") or "today's article")[:200],
            history=history,
            user_speech=transcript[:500],
            native_lang=resolve_language_name(session["native_lang"]),
        )
        return client.chat_json(
            system, "Continue the conversation.", task="convo")

    # ── TTS ───────────────────────────────────────────────────────

    def _synth_line(self, profile_name: str, text: str, lang_code: str,
                    level: str) -> Optional[str]:
        from tts import synthesize

        profile = self.config.get("profiles", {}).get(profile_name, {})
        output_dir = os.path.join(str(OUTPUT_DIR), profile_name, "convo")
        try:
            return synthesize(
                text=text,
                language_id=lang_code,
                config=self.config,
                output_dir=output_dir,
                voice=profile.get("tts_voice", TTS_DEFAULT_VOICE),
                speed=tts_speed_for_level(level),
            )
        except Exception as e:
            logger.warning("Convo TTS failed: %s", e)
            return None

    # ── Telegram helpers ──────────────────────────────────────────

    def _turn_caption(self, session: dict, turn_no: int, reply: str,
                      translation: str) -> str:
        native_name = resolve_language_name(session["native_lang"])
        parts = [
            f"🗣 <b>Conversation {turn_no}/{session['turns_total']}</b>"
            f" · topic: <i>{html.escape(session['topic'])}</i>",
            "",
            f"<tg-spoiler>{html.escape(reply)}</tg-spoiler>",
        ]
        if translation:
            parts += ["", f"<i>{html.escape(native_name)}:</i> "
                          f"<tg-spoiler>{html.escape(translation)}</tg-spoiler>"]
        parts += ["", "🎤 Record your answer as a voice message."]
        return "\n".join(parts)

    async def _send(self, chat_id: int, text: str, reply_markup=None):
        bot = await self.bot._get_aiogram_bot()
        return await bot.send_message(
            chat_id=chat_id, text=text, parse_mode="HTML",
            reply_markup=reply_markup,
        )

    async def _send_audio(self, chat_id: int, wav_path: str, caption: str):
        from aiogram.methods import SendAudio
        from aiogram.types.input_file import FSInputFile

        bot = await self.bot._get_aiogram_bot()
        try:
            return await bot(SendAudio(
                chat_id=chat_id,
                audio=FSInputFile(path=wav_path,
                                  filename=os.path.basename(wav_path)),
                caption=caption,
                parse_mode="HTML",
            ))
        except Exception as e:
            logger.error("Failed to send convo audio: %s", e)
            return None

    async def _delete(self, message):
        if message is None:
            return
        try:
            await message.delete()
        except Exception as e:
            logger.debug("Could not delete placeholder: %s", e)

    @staticmethod
    def _cleanup(work_dir: str, *paths: str):
        for p in paths:
            try:
                if p and os.path.isfile(p):
                    os.remove(p)
            except OSError:
                pass
