#!/usr/bin/env python3
"""
Conversation practice for LinguaDaily — speaking + listening.

The user starts a short spoken conversation with /convo.  Each turn:
  1. The bot sends a TTS audio line (the "partner"), plus the line text
     and its translation, both hidden behind Telegram spoilers.
  2. The user records a voice-message reply.
  3. The reply is transcribed (STT endpoint — see src/stt.py) and scored;
     the partner's next line is generated by an LLM (ideally a small,
     fast model — configure via llm.task_models.convo or a per-profile
     llm_convo_model override).

The conversation topic is the profile's latest delivered lesson, and the
language level follows the profile's CEFR target_level.  The partner's
lines always end with a question so the learner always knows what to say.
B1+ learners additionally get a short "how to say it better" tip in the
feedback (a dedicated prompt variant, not a conditional instruction).

All user-facing messages are shown in the profile's `native_language`
(the language the user understands; English is the fallback).  The final
summary includes the full exchange — the partner's lines alongside the
user's transcribed answers and scores.

Audio is ephemeral: TTS lines are deleted right after being sent and
voice notes right after transcription, so nothing accumulates in
output/<profile>/convo/.

Config (config.json):
    "stt": {"base_url": "...", "model": "..."}   # required for /convo
    "llm": {"task_models": {"convo": "small-model"}}  # optional
    "convo": {"turns": 6}                        # optional default turns

Usage (import):
    from src.convo import ConvoHandler
    handler = ConvoHandler(config, telegram_bot_instance)
    await handler.start_convo(chat_id, profile_name)
    await handler.handle_voice(message)
"""

import asyncio
import html
import logging
import os
import time
from typing import Optional

from config import (
    CONVO_DEFAULT_TURNS,
    CONVO_MAX_TURNS,
    CONVO_MIN_TURNS,
    CONVO_SESSION_TIMEOUT_SECS,
    DEFAULT_LEARNING_LANGUAGE,
    DEFAULT_NATIVE_LANGUAGE,
    OUTPUT_DIR,
    TTS_DEFAULT_VOICE,
    resolve_language_name,
    tts_speed_for_level,
)
from stt import is_configured, transcribe, voice_to_wav

logger = logging.getLogger(__name__)


# ── Prompts ─────────────────────────────────────────────────────────

CONVO_OPEN_SYSTEM = """You are a friendly conversation partner for a {level} learner of {language_name}.

The conversation is about the learner's daily article: "{topic}".

Rules:
- Write ONE natural opening line in {language_name} about the topic that
  ENDS WITH A QUESTION the learner can answer by speaking.
- 1-2 short sentences, simple {level}-level vocabulary.
- "translation": the line translated into {native_lang}.

Respond with ONLY a JSON object:
{{"reply": "...", "translation": "..."}}"""

# Next-line prompt for A1/A2 (and 'original') learners — feedback stays
# minimal: at this stage it is enough to understand the language.
CONVO_NEXT_SYSTEM = """You are a friendly conversation partner for a {level} learner of {language_name}.

The conversation is about the learner's daily article: "{topic}".
The learner answers by SPEAKING; their utterance was transcribed by speech
recognition and may contain recognition errors.

{history}The learner just said: "{user_speech}"

Respond with ONLY a JSON object:
- "feedback": brief feedback in {native_lang}, max 2 sentences. Note the most
  important language error if there is one; otherwise confirm it was fine.
  Concise and factual — no praise padding.
- "score": integer 0-100 for grammar and word choice. Fair scale:
  85-100 correct and natural · 60-84 understandable, minor errors ·
  40-59 significant errors · below 40 mostly wrong.
- "reply": your next line in {language_name} — a natural response to what they
  said that ENDS WITH A QUESTION the learner can answer, 1-2 short sentences,
  simple {level}-level vocabulary. Do not repeat a line or question you
  already used.
- "translation": the reply translated into {native_lang}."""

# Next-line prompt for B1+ learners — the feedback additionally carries one
# short tip on how to say the idea better, so the learner actively improves
# their phrasing.  A dedicated prompt (instead of a conditional instruction)
# keeps the behaviour deterministic on small models.
CONVO_NEXT_SYSTEM_TIPS = """You are a friendly conversation partner for a {level} learner of {language_name}.

The conversation is about the learner's daily article: "{topic}".
The learner answers by SPEAKING; their utterance was transcribed by speech
recognition and may contain recognition errors.

{history}The learner just said: "{user_speech}"

Respond with ONLY a JSON object:
- "feedback": brief feedback in {native_lang}, max 3 sentences. Note the most
  important language error if there is one; otherwise confirm it was fine.
  Then give ONE short tip on how to say the same idea more naturally or
  accurately — when there is something to improve, show a better phrasing in
  {language_name}. Concise and factual — no praise padding.
- "score": integer 0-100 for grammar and word choice. Fair scale:
  85-100 correct and natural · 60-84 understandable, minor errors ·
  40-59 significant errors · below 40 mostly wrong.
- "reply": your next line in {language_name} — a natural response to what they
  said that ENDS WITH A QUESTION the learner can answer, 1-2 short sentences,
  simple {level}-level vocabulary. Do not repeat a line or question you
  already used.
- "translation": the reply translated into {native_lang}."""


def _level_label(level: str) -> str:
    """CEFR level for prompts — 'original' becomes a plain description."""
    lvl = (level or "original").upper()
    if lvl in ("A1", "A2", "B1", "B2", "C1", "C2"):
        return lvl
    return "A2-B1 (simple)"


def _is_advanced(level: str) -> bool:
    """B1+ levels get the prompt variant with phrasing tips."""
    return (level or "").strip().upper() in ("B1", "B2", "C1", "C2")


def _clamp_turns(turns: Optional[int]) -> int:
    if not turns:
        return CONVO_DEFAULT_TURNS
    return max(CONVO_MIN_TURNS, min(CONVO_MAX_TURNS, int(turns)))


# ── Localized user-facing strings ─────────────────────────────────
#
# Keyed by the profile's `native_language` — the language the user
# understands.  English is the fallback for any code without a table.

_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "stt_not_configured": (
            "⚠️ Speech-to-text is not configured.\n"
            "Add an <code>stt</code> section to config.json "
            "(base_url + model) and restart."),
        "tts_disabled": (
            "⚠️ TTS is disabled for this profile — "
            "conversation practice needs audio."),
        "no_llm": (
            "⚠️ No LLM model configured — set <code>llm.default_model</code> "
            "(optionally a small fast one via <code>llm.task_models.convo</code>)."),
        "no_lesson": "⚠️ No lesson yet — run /another first, then try /convo.",
        "preparing": "🎧 Preparing your conversation…",
        "llm_unavailable": (
            "⚠️ Could not start the conversation — LLM unavailable. Try again."),
        "no_session": "No active conversation — start one with /convo.",
        "busy": "⏳ Still working on the last answer — one moment.",
        "transcribing": "🎧 Transcribing…",
        "processing_error": "⚠️ Something went wrong — try recording again.",
        "download_failed": "⚠️ Could not download your voice message.",
        "ffmpeg_missing": (
            "⚠️ Could not process the audio — is ffmpeg installed on the daemon?"),
        "stt_failed": "⚠️ Transcription failed — is the STT endpoint up? Try again.",
        "empty_transcript": "🤔 I couldn't catch anything — try again?",
        "tutor_unavailable": "⚠️ The tutor is unavailable — try recording again.",
        "tts_failed": "(⚠️ TTS failed — text only)",
        "turn_header": "✅ <b>Turn {turn}/{total}</b> · score: <b>{score}/100</b>",
        "summary_title": "🏁 <b>Conversation complete!</b>",
        "summary_topic": "Topic",
        "summary_avg": "Average score",
        "summary_note": "(Scores are based on the transcribed words.)",
        "caption_header": "🗣 <b>Conversation {turn}/{total}</b> · topic",
        "caption_prompt": "🎤 Record your answer as a voice message.",
        "partner": "🗣 Partner",
        "you": "🎤 You",
    },
    "cs": {
        "stt_not_configured": (
            "⚠️ Přepis řeči (speech-to-text) není nakonfigurovaný.\n"
            "Přidejte sekci <code>stt</code> do config.json "
            "(base_url + model) a restartujte."),
        "tts_disabled": (
            "⚠️ TTS je pro tento profil vypnutý — "
            "cvičení konverzace potřebuje zvuk."),
        "no_llm": (
            "⚠️ Není nakonfigurovaný žádný LLM model — nastavte "
            "<code>llm.default_model</code> (volitelně malý rychlý přes "
            "<code>llm.task_models.convo</code>)."),
        "no_lesson": "⚠️ Zatím žádná lekce — nejdřív spusťte /another, pak zkuste /convo.",
        "preparing": "🎧 Připravuji vaši konverzaci…",
        "llm_unavailable": (
            "⚠️ Nedaří se nastartovat konverzaci — LLM není dostupné. Zkuste to znovu."),
        "no_session": "Žádná aktivní konverzace — spusťte ji příkazem /convo.",
        "busy": "⏳ Stále zpracovávám poslední odpověď — chvilku.",
        "transcribing": "🎧 Přepisuji…",
        "processing_error": "⚠️ Něco se pokazilo — zkuste to nahrát znovu.",
        "download_failed": "⚠️ Nedaří se stáhnout vaši hlasovou zprávu.",
        "ffmpeg_missing": "⚠️ Zvuk se nepodařilo zpracovat — je na démonu nainstalovaný ffmpeg?",
        "stt_failed": "⚠️ Přepis selhal — je STT endpoint dostupný? Zkuste to znovu.",
        "empty_transcript": "🤔 Nic jsem nepochopil — zkuste to znovu?",
        "tutor_unavailable": "⚠️ Tutořitel není dostupný — zkuste to nahrát znovu.",
        "tts_failed": "(⚠️ TTS selhalo — jen text)",
        "turn_header": "✅ <b>Kolo {turn}/{total}</b> · skóre: <b>{score}/100</b>",
        "summary_title": "🏁 <b>Konverzace dokončena!</b>",
        "summary_topic": "Téma",
        "summary_avg": "Průměrné skóre",
        "summary_note": "(Skóre je založeno na přepsaných slovech.)",
        "caption_header": "🗣 <b>Konverzace {turn}/{total}</b> · téma",
        "caption_prompt": "🎤 Nahrajte svou odpověď jako hlasovou zprávu.",
        "partner": "🗣 Partner",
        "you": "🎤 Vy",
    },
}


def _t(lang_code: str, key: str, **fmt) -> str:
    """Localized user-facing string for the profile's native language.

    Falls back to English for unknown codes or missing keys.
    """
    table = _STRINGS.get(lang_code) or _STRINGS["en"]
    template = table.get(key) or _STRINGS["en"][key]
    return template.format(**fmt) if fmt else template


# ── Handler ─────────────────────────────────────────────────────────

class ConvoHandler:
    """Manages short spoken conversation sessions inside Telegram.

    Session state lives in self._sessions[chat_id]; the Telegram bot
    routes /convo and voice messages here (see telegram_bot.py).
    """

    def __init__(self, config: dict, telegram_bot):
        self.config = config
        self.bot = telegram_bot
        self._sessions: dict[int, dict] = {}
        self._llama_client = None

    # ── Session lifecycle ─────────────────────────────────────────

    def _get_session(self, chat_id: int) -> Optional[dict]:
        """Return the active session or None if expired/missing."""
        session = self._sessions.get(chat_id)
        if not session:
            return None
        if time.time() - session["created_at"] > CONVO_SESSION_TIMEOUT_SECS:
            self._end_session(chat_id)
            if not session.get("busy"):
                self._sweep_profile_audio(session["profile"])
            return None
        # Refresh the inactivity timeout
        session["created_at"] = time.time()
        return session

    def _end_session(self, chat_id: int):
        self._sessions.pop(chat_id, None)

    def end_convo(self, chat_id: int) -> bool:
        """End the active session for this chat (e.g. via /stop).

        Returns True if a session was active, False otherwise.
        """
        chat_id = int(chat_id)
        session = self._get_session(chat_id)
        if session is None:
            return False
        self._end_session(chat_id)
        # Discard leftover audio (skip while a turn is still in flight)
        if not session.get("busy"):
            self._sweep_profile_audio(session["profile"])
        return True

    def _sweep_profile_audio(self, profile_name: str):
        """Delete leftover convo audio for a profile.

        Normal operation discards each file right after use; this picks
        up stragglers from failed turns or a crashed session so nothing
        accumulates in output/<profile>/convo/.
        """
        work_dir = os.path.join(str(OUTPUT_DIR), profile_name, "convo")
        if not os.path.isdir(work_dir):
            return
        removed = 0
        for name in os.listdir(work_dir):
            if ((name.startswith("lingua_") and name.endswith(".wav"))
                    or (name.startswith("voice_")
                        and name.endswith((".ogg", ".wav")))):
                self._cleanup(work_dir, os.path.join(work_dir, name))
                removed += 1
        if removed:
            logger.info("Convo cleanup: removed %d leftover file(s) from %s",
                        removed, work_dir)

    def _get_llama_client(self, profile_name: str):
        if (self._llama_client is None
                or self._llama_client.profile_name != profile_name):
            from llama_client import LlamaClient
            self._llama_client = LlamaClient(
                config=self.config, profile_name=profile_name
            )
        return self._llama_client

    # ── Public API ────────────────────────────────────────────────

    async def start_convo(self, chat_id: int, profile_name: str,
                          turns: Optional[int] = None):
        """Start a conversation session for the profile's latest lesson."""
        # Pick up config changes made through the web UI
        self.config = self.bot.config or self.config
        self._end_session(chat_id)
        # Discard audio left over from a previous (crashed?) session
        self._sweep_profile_audio(profile_name)

        profile = self.config.get("profiles", {}).get(profile_name, {})
        lang_code = profile.get("learning_language", DEFAULT_LEARNING_LANGUAGE)
        native = profile.get("native_language", DEFAULT_NATIVE_LANGUAGE)
        level = profile.get("target_level", "original")

        # ── Prerequisites ─────────────────────────────────────────
        if not is_configured(self.config):
            await self._send(chat_id, _t(native, "stt_not_configured"))
            return
        if not profile.get("use_tts", True) or not self.config.get("tts"):
            await self._send(chat_id, _t(native, "tts_disabled"))
            return

        client = self._get_llama_client(profile_name)
        if not client.resolve_model("convo"):
            await self._send(chat_id, _t(native, "no_llm"))
            return

        lesson = None
        try:
            lesson = self.bot.db.get_latest_lesson(profile_name)
        except Exception as e:
            logger.error("Could not fetch latest lesson: %s", e)
        if not lesson or not (lesson.get("title") or "").strip():
            await self._send(chat_id, _t(native, "no_lesson"))
            return

        if not turns:
            turns = (self.config.get("convo", {}) or {}).get("turns")
        turns = _clamp_turns(turns)
        placeholder = await self._send(chat_id, _t(native, "preparing"))

        # ── Opening line (LLM) ────────────────────────────────────
        data = await asyncio.to_thread(
            self._generate_opening, client, lesson, lang_code, native, level)
        if not data or not str(data.get("reply", "")).strip():
            await self._delete(placeholder)
            await self._send(chat_id, _t(native, "llm_unavailable"))
            return
        reply = str(data["reply"]).strip()[:300]
        translation = str(data.get("translation", "")).strip()[:300]

        session = {
            "mode": "convo",
            "profile": profile_name,
            "turns_total": turns,
            "topic": lesson.get("title", ""),
            "level": level,
            "lang_code": lang_code,
            "native_lang": native,
            "lines": [],          # [{"transcript": str, "score": int}, …]
            "history": [],        # [{"role": "partner"|"learner", "text": str}, …]
            "created_at": time.time(),
            "busy": False,
        }
        self._sessions[chat_id] = session
        session["history"].append({"role": "partner", "text": reply})

        # ── Audio (TTS) ───────────────────────────────────────────
        await self._delete(placeholder)
        await self._send_turn_audio(chat_id, session, 1, reply, translation)
        logger.info("Convo started for chat %d (profile '%s', %d turns, "
                    "topic: %s)", chat_id, profile_name, turns,
                    session["topic"])

    async def handle_voice(self, message):
        """Handle a voice message — the user's spoken answer."""
        chat_id = message.chat.id
        session = self._get_session(chat_id)
        if not session:
            await self._send(chat_id, _t(DEFAULT_NATIVE_LANGUAGE, "no_session"))
            return
        native = session["native_lang"]
        if session.get("busy"):
            await self._send(chat_id, _t(native, "busy"))
            return

        session["busy"] = True
        placeholder = await self._send(chat_id, _t(native, "transcribing"))
        try:
            await self._process_voice(message, session, chat_id)
        except Exception as e:
            logger.error("Convo voice processing failed: %s", e, exc_info=True)
            await self._send(chat_id, _t(native, "processing_error"))
        finally:
            session["busy"] = False
            await self._delete(placeholder)

    # ── Voice pipeline ────────────────────────────────────────────

    async def _process_voice(self, message, session: dict, chat_id: int):
        """Download → convert → transcribe → score → next line."""
        profile = session["profile"]
        lang_code = session["lang_code"]

        # 1) Download the Telegram voice note (OGG/Opus)
        bot = await self.bot._get_aiogram_bot()
        work_dir = os.path.join(str(OUTPUT_DIR), profile, "convo")
        os.makedirs(work_dir, exist_ok=True)
        ogg_path = os.path.join(work_dir, f"voice_{int(time.time() * 1000)}.ogg")
        try:
            # bot.download() accepts the Voice object directly (it reads file_id)
            await bot.download(message.voice, destination=ogg_path)
        except Exception as e:
            logger.error("Could not download voice message: %s", e)
            self._cleanup(work_dir, ogg_path)
            await self._send(chat_id, _t(session["native_lang"], "download_failed"))
            return

        # 2) Convert to WAV (ffmpeg)
        wav_path = await asyncio.to_thread(voice_to_wav, ogg_path, work_dir)
        if not wav_path:
            self._cleanup(work_dir, ogg_path)
            await self._send(
                chat_id, _t(session["native_lang"], "ffmpeg_missing"))
            return

        # 3) Transcribe (STT endpoint)
        transcript = await asyncio.to_thread(
            transcribe, wav_path, lang_code, self.config)
        self._cleanup(work_dir, ogg_path, wav_path)

        if transcript is None:
            await self._send(
                chat_id, _t(session["native_lang"], "stt_failed"))
            return
        if not transcript:
            await self._send(
                chat_id, _t(session["native_lang"], "empty_transcript"))
            return

        # 4) Score + next line (LLM)
        client = self._get_llama_client(profile)
        data = await asyncio.to_thread(
            self._generate_next, client, session, transcript)
        if not data or not str(data.get("reply", "")).strip():
            await self._send(
                chat_id, _t(session["native_lang"], "tutor_unavailable"))
            return

        score = max(0, min(100, int(data.get("score", 0) or 0)))
        feedback = str(data.get("feedback", "")).strip()[:500]
        reply = str(data["reply"]).strip()[:300]
        translation = str(data.get("translation", "")).strip()[:300]

        session["lines"].append({"transcript": transcript, "score": score})
        session["history"].append({"role": "learner", "text": transcript[:300]})
        session["history"].append({"role": "partner", "text": reply})
        turn_no = len(session["lines"])
        total = session["turns_total"]

        # 5) Feedback message
        fb_lines = [
            _t(session["native_lang"], "turn_header",
               turn=turn_no, total=total, score=score),
            f"💬 <i>“{html.escape(transcript)}”</i>",
        ]
        if feedback:
            fb_lines += ["", html.escape(feedback)]
        await self._send(chat_id, "\n".join(fb_lines))

        # 6) Summary or next line
        # If the session was ended (e.g. /stop) or replaced while we were
        # processing, don't send the stale reply.
        if self._sessions.get(chat_id) is not session:
            return
        if turn_no >= total:
            await self._send_summary(chat_id, session)
            self._end_session(chat_id)
            # This turn's own files are already discarded — sweep stragglers
            self._sweep_profile_audio(session["profile"])
            return

        await self._send_turn_audio(
            chat_id, session, turn_no + 1, reply, translation)

    async def _send_summary(self, chat_id: int, session: dict):
        """Final summary: the full exchange (partner + user lines) + scores."""
        native = session["native_lang"]
        scores = [l["score"] for l in session["lines"]]
        avg = round(sum(scores) / len(scores)) if scores else 0
        # Partner lines the user actually heard: one per turn (the trailing
        # history entry is the unsent closing line, if any).
        partner_lines = [e["text"] for e in session["history"]
                         if e["role"] == "partner"]
        lines = [
            _t(native, "summary_title"),
            f"{_t(native, 'summary_topic')}: <i>{html.escape(session['topic'])}</i>",
            f"{_t(native, 'summary_avg')}: <b>{avg}/100</b>",
            "",
        ]
        for i, l in enumerate(session["lines"], 1):
            partner = partner_lines[i - 1] \
                if i - 1 < len(partner_lines) else ""
            lines.append(
                f"{i}. {_t(native, 'partner')}: "
                f"<i>“{html.escape(partner)}”</i>")
            lines.append(
                f"   {_t(native, 'you')}: "
                f"<i>“{html.escape(l['transcript'])}”</i> — {l['score']}/100")
        lines += ["", f"<i>{_t(native, 'summary_note')}</i>"]
        await self._send(chat_id, "\n".join(lines))

    async def _send_turn_audio(self, chat_id: int, session: dict, turn_no: int,
                               reply: str, translation: str):
        """Synthesize a partner line, send it, then delete the audio.

        The WAV is discarded as soon as it has been sent — there is no
        point in keeping it and it stops the output dir from growing.
        Falls back to a text-only message if sending the audio fails.
        """
        caption = self._turn_caption(session, turn_no, reply, translation)
        wav = await asyncio.to_thread(
            self._synth_line, session["profile"], reply,
            session["lang_code"], session["level"])
        if wav:
            sent = await self._send_audio(chat_id, wav, caption)
            self._cleanup(os.path.dirname(wav), wav)
            if sent is not None:
                return
        await self._send(
            chat_id, _t(session["native_lang"], "tts_failed") + "\n" + caption)

    # ── LLM calls ─────────────────────────────────────────────────

    def _generate_opening(self, client, lesson: dict, lang_code: str,
                          native: str, level: str) -> Optional[dict]:
        system = CONVO_OPEN_SYSTEM.format(
            level=_level_label(level),
            language_name=resolve_language_name(lang_code),
            topic=(lesson.get("title") or "today's article")[:200],
            native_lang=resolve_language_name(native),
        )
        return client.chat_json(
            system, "Start the conversation.", task="convo")

    def _generate_next(self, client, session: dict,
                       transcript: str) -> Optional[dict]:
        # Full exchange history (partner + learner lines) so the partner
        # keeps the conversation coherent and natural
        entries = session.get("history", [])
        history = ""
        if entries:
            history = "Conversation so far:\n" + "\n".join(
                f"{entry['role'].capitalize()}: \"{entry['text']}\""
                for entry in entries
            ) + "\n\n"
        template = (CONVO_NEXT_SYSTEM_TIPS if _is_advanced(session["level"])
                    else CONVO_NEXT_SYSTEM)
        system = template.format(
            level=_level_label(session["level"]),
            language_name=resolve_language_name(session["lang_code"]),
            topic=(session.get("topic") or "today's article")[:200],
            history=history,
            user_speech=transcript[:500],
            native_lang=resolve_language_name(session["native_lang"]),
        )
        return client.chat_json(
            system, "Continue the conversation.", task="convo")

    # ── TTS ───────────────────────────────────────────────────────

    def _synth_line(self, profile_name: str, text: str, lang_code: str,
                    level: str) -> Optional[str]:
        from tts import synthesize

        profile = self.config.get("profiles", {}).get(profile_name, {})
        output_dir = os.path.join(str(OUTPUT_DIR), profile_name, "convo")
        try:
            return synthesize(
                text=text,
                language_id=lang_code,
                config=self.config,
                output_dir=output_dir,
                voice=profile.get("tts_voice", TTS_DEFAULT_VOICE),
                speed=tts_speed_for_level(level),
            )
        except Exception as e:
            logger.warning("Convo TTS failed: %s", e)
            return None

    # ── Telegram helpers ──────────────────────────────────────────

    def _turn_caption(self, session: dict, turn_no: int, reply: str,
                      translation: str) -> str:
        native = session["native_lang"]
        native_name = resolve_language_name(native)
        parts = [
            _t(native, "caption_header",
               turn=turn_no, total=session["turns_total"])
            + f": <i>{html.escape(session['topic'])}</i>",
            "",
            f"<tg-spoiler>{html.escape(reply)}</tg-spoiler>",
        ]
        if translation:
            parts += ["", f"<i>{html.escape(native_name)}:</i> "
                          f"<tg-spoiler>{html.escape(translation)}</tg-spoiler>"]
        parts += ["", _t(native, "caption_prompt")]
        return "\n".join(parts)

    async def _send(self, chat_id: int, text: str, reply_markup=None):
        bot = await self.bot._get_aiogram_bot()
        return await bot.send_message(
            chat_id=chat_id, text=text, parse_mode="HTML",
            reply_markup=reply_markup,
        )

    async def _send_audio(self, chat_id: int, wav_path: str, caption: str):
        from aiogram.methods import SendAudio
        from aiogram.types.input_file import FSInputFile

        bot = await self.bot._get_aiogram_bot()
        try:
            return await bot(SendAudio(
                chat_id=chat_id,
                audio=FSInputFile(path=wav_path,
                                  filename=os.path.basename(wav_path)),
                caption=caption,
                parse_mode="HTML",
            ))
        except Exception as e:
            logger.error("Failed to send convo audio: %s", e)
            return None

    async def _delete(self, message):
        if message is None:
            return
        try:
            await message.delete()
        except Exception as e:
            logger.debug("Could not delete placeholder: %s", e)

    @staticmethod
    def _cleanup(work_dir: str, *paths: str):
        for p in paths:
            try:
                if p and os.path.isfile(p):
                    os.remove(p)
            except OSError:
                pass
