#!/usr/bin/env python3
"""
Vocabulary processor for LinguaDaily standalone daemon.

Manages per-profile vocabulary markdown files — reading existing entries,
appending new words extracted by the LLM, and tracking frequency / last-seen date.

Usage (import):
    from src.processor import LinguaProcessor
    proc = LinguaProcessor(target_lang_name="German", profile="krystof")
    proc.update_vocab(vocab_list)  # list of {word, meaning} dicts

Vocabulary file format (data/<profile>/vocabulary.md):
    | Word | Meaning | Frequency | Last Seen |
    | :--- | :--- | :--- | :--- |
"""

import os
from datetime import date

from config import PROJECT_DIR


class LinguaProcessor:
    """Manages vocabulary persistence for a single profile."""

    def __init__(self, target_lang_name="German", profile="default",
                 vocab_path=None):
        self.target_lang_name = target_lang_name
        self.profile = profile

        # Resolve vocab_path: explicit > per-profile default
        if vocab_path:
            if not os.path.isabs(vocab_path):
                self.vocab_path = PROJECT_DIR / vocab_path
            else:
                self.vocab_path = vocab_path
        else:
            self.vocab_path = PROJECT_DIR / "data" / profile / "vocabulary.md"

    # ── File I/O ───────────────────────────────────────────────────

    def _ensure_vocab_file(self):
        """Create the vocabulary markdown file if it doesn't exist."""
        if os.path.exists(self.vocab_path):
            return

        os.makedirs(os.path.dirname(self.vocab_path) or ".", exist_ok=True)
        with open(self.vocab_path, 'w', encoding='utf-8') as f:
            f.write(f"# Vocabulary Database — Profile: {self.profile}\n\n")
            f.write("*Auto-generated by LinguaDaily*\n\n")
            f.write("| Word | Meaning | Frequency | Last Seen |\n")
            f.write("| :--- | :--- | :--- | :--- |\n")

    def _read_existing_vocab(self):
        """Read existing vocabulary entries as {word_lower: frequency}."""
        existing = {}
        if not os.path.exists(self.vocab_path):
            return existing

        with open(self.vocab_path, 'r', encoding='utf-8') as f:
            for line in f:
                if not line.startswith("|") or "|" not in line[1:]:
                    continue
                parts = [p.strip() for p in line.strip().strip("|").split("|")]
                # Skip header, separator rows, and empty entries
                if len(parts) < 3:
                    continue
                word = parts[0].lower()
                if word == "word" or not word or word.startswith(":"):
                    continue
                existing[word] = (
                    int(parts[2]) if parts[2].isdigit() else 1
                )
        return existing

    # ── Public API ─────────────────────────────────────────────────

    def update_vocab(self, words):
        """
        Append new vocabulary words to the markdown vocabulary file.

        Parameters
        ----------
        words : list
            List of dicts {word, meaning} (from llama_client.extract_vocab)
            or plain strings. Duplicate words are skipped; new words get
            frequency 1 and today's date.
        """
        os.makedirs(os.path.dirname(self.vocab_path) or ".", exist_ok=True)
        self._ensure_vocab_file()

        today = date.today().isoformat()
        existing = self._read_existing_vocab()

        with open(self.vocab_path, 'a', encoding='utf-8') as f:
            for entry in words:
                if isinstance(entry, dict):
                    w = str(entry.get("word", "")).strip().lower()
                    m = entry.get("meaning", "(new)")
                else:
                    w = str(entry).strip().lower()
                    m = "(new)"

                if not w or w in existing:
                    continue

                freq = existing.get(w, 0) + 1
                f.write(f"| {w} | {m} | {freq} | {today} |\n")
                existing[w] = freq


# ── CLI entry point ────────────────────────────────────────────────

def main():
    """CLI for testing vocabulary updates.

    Usage:
        python3 src/processor.py --profile krystof --words '{"word":"Haus","meaning":"house"}'
    """
    import argparse

    parser = argparse.ArgumentParser(description="Vocabulary processor")
    parser.add_argument("--profile", "-p", default="default", help="Profile name")
    parser.add_argument("--lang", "-l", default="German", help="Target language name")
    parser.add_argument("--words", "-w", default=None,
                        help='JSON array of {word, meaning} dicts')
    args = parser.parse_args()

    proc = LinguaProcessor(target_lang_name=args.lang, profile=args.profile)

    if args.words:
        import json
        words = json.loads(args.words)
        proc.update_vocab(words)
        print(f"Updated vocabulary for '{args.profile}' → {proc.vocab_path}")


if __name__ == "__main__":
    main()
