import os
from datetime import date


class LinguaProcessor:
    def __init__(self, target_lang_name="German", profile="default", vocab_path=None):
        self.target_lang_name = target_lang_name
        self.profile = profile

        # Resolve vocab_path: explicit > per-profile > legacy default
        self.script_dir = os.path.dirname(os.path.abspath(__file__))
        if vocab_path:
            if not os.path.isabs(vocab_path):
                self.vocab_path = os.path.join(self.script_dir, "..", vocab_path)
            else:
                self.vocab_path = vocab_path
        else:
            # Default: data/<profile>/vocabulary.md
            self.vocab_path = os.path.join(
                self.script_dir, "..", "data", profile, "vocabulary.md"
            )

    def process_daily_content(self, text, source_lang="en", title=""):
        """
        Prepare content for the Agent to translate.
        Returns a structured dict with the source text, title, and metadata.
        The orchestrator handles fetching and preparing content for translation.
        """
        print(f"Processing content for {self.target_lang_name} (profile: {self.profile})...")
        print(f"Title: {title}")
        print(f"Source text length: {len(text)} chars, {len(text.split())} words")

        # Return structured data for the Agent to handle
        return {
            "title": title,
            "source_text": text,
            "source_lang": source_lang,
            "target_lang": self.target_lang_name,
            "profile": self.profile,
            "instruction": (
                f"Translate the following article from {source_lang} to {self.target_lang_name}. "
                f"Then extract useful vocabulary words (nouns, verbs, adjectives) that a learner "
                f"of {self.target_lang_name} should know. Update the vocabulary database."
            ),
        }

    def _ensure_vocab_file(self):
        if os.path.exists(self.vocab_path):
            return

        os.makedirs(os.path.dirname(self.vocab_path), exist_ok=True)
        with open(self.vocab_path, 'w', encoding='utf-8') as f:
            f.write(f"# Vocabulary Database — Profile: {self.profile}\n\n")
            f.write("*Auto-generated by LinguaDaily*\n\n")
            f.write("| Word | Meaning | Frequency | Last Seen |\n")
            f.write("| :--- | :--- | :--- | :--- |\n")

    def _read_existing_vocab(self):
        existing = {}
        if not os.path.exists(self.vocab_path):
            return existing

        with open(self.vocab_path, 'r', encoding='utf-8') as f:
            for line in f:
                if not line.startswith("|") or "|" not in line[1:]:
                    continue
                parts = [p.strip() for p in line.strip().strip("|").split("|")]
                if len(parts) >= 3 and parts[0].lower() != "word":
                    existing[parts[0].lower()] = int(parts[2]) if parts[2].isdigit() else 1
        return existing

    def update_vocab(self, words):
        """
        Append new vocabulary words to the markdown vocabulary file.
        Words can be a list of strings or a list of dicts {word, meaning, freq}.
        """
        os.makedirs(os.path.dirname(self.vocab_path) or ".", exist_ok=True)
        self._ensure_vocab_file()

        today = date.today().isoformat()
        existing = self._read_existing_vocab()

        with open(self.vocab_path, 'a', encoding='utf-8') as f:
            for entry in words:
                if isinstance(entry, dict):
                    w = str(entry.get("word", "")).strip().lower()
                    m = entry.get("meaning", "(new)")
                else:
                    w = str(entry).strip().lower()
                    m = "(new)"

                if not w or w in existing:
                    continue

                freq = existing.get(w, 0) + 1
                f.write(f"| {w} | {m} | {freq} | {today} |\n")
                existing[w] = freq


if __name__ == "__main__":
    # Standalone test: fetch a random article and prepare it for translation
    from src.orchestrator import fetch_random_wiki_article
    title, text = fetch_random_wiki_article()
    if title and text:
        processor = LinguaProcessor(target_lang_name="German", profile="krystof")
        result = processor.process_daily_content(text, title=title)
        print(f"\nInstruction for Agent:\n{result['instruction']}")
