import os
from datetime import date

class LinguaProcessor:
    def __init__(self, target_lang_name="German", vocab_path="data/vocabulary.md"):
        self.target_lang_name = target_lang_name
        # Resolve vocab_path relative to this script's location
        self.script_dir = os.path.dirname(os.path.abspath(__file__))
        if not os.path.isabs(vocab_path):
            self.vocab_path = os.path.join(self.script_dir, "..", vocab_path)
        else:
            self.vocab_path = vocab_path

    def process_daily_content(self, text, source_lang="en", title=""):
        """
        Prepare content for the Agent to translate.
        Returns a structured dict with the source text, title, and metadata.
        The Agent (OpenClaw) handles the actual LLM translation.
        """
        print(f"Processing content for {self.target_lang_name}...")
        print(f"Title: {title}")
        print(f"Source text length: {len(text)} chars, {len(text.split())} words")

        # Return structured data for the Agent to handle
        return {
            "title": title,
            "source_text": text,
            "source_lang": source_lang,
            "target_lang": self.target_lang_name,
            "instruction": (
                f"Translate the following article from {source_lang} to {self.target_lang_name}. "
                f"Then extract useful vocabulary words (nouns, verbs, adjectives) that a learner "
                f"of {self.target_lang_name} should know. Update the vocabulary database."
            ),
        }

    def update_vocab(self, words):
        """
        Append new vocabulary words to the markdown vocabulary file.
        Words can be a list of strings or a list of dicts {word, meaning, freq}.
        """
        os.makedirs(os.path.dirname(self.vocab_path) or ".", exist_ok=True)
        
        today = date.today().isoformat()
        
        # Create file with header if it doesn't exist
        if not os.path.exists(self.vocab_path):
            with open(self.vocab_path, 'w') as f:
                f.write("# Vocabulary Database\n\n")
                f.write(f"*Auto-generated by OpenClaw-Lingua*\n\n")
                f.write("| Word | Meaning | Frequency | Last Seen |\n")
                f.write("| :--- | :--- | :--- | :--- |\n")
        
        # Read existing words to track frequency
        existing = {}
        with open(self.vocab_path, 'r') as f:
            for line in f:
                if line.startswith("|") and "|" in line[1:]:
                    parts = [p.strip() for p in line.strip().strip("|").split("|")]
                    if len(parts) >= 3 and parts[0] not in ("Word", ""):
                        existing[parts[0]] = int(parts[2]) if parts[2].isdigit() else 1
        
        # Append or update
        with open(self.vocab_path, 'a') as f:
            for word in words:
                if isinstance(word, dict):
                    w = word.get("word", "").lower()
                    m = word.get("meaning", "(new)")
                    freq = existing.get(w, 0) + 1
                else:
                    w = str(word).lower()
                    m = "(new)"
                    freq = existing.get(w, 0) + 1
                
                if w and w not in existing:  # Only append truly new words
                    f.write(f"| {w} | {m} | {freq} | {today} |\n")

if __name__ == "__main__":
    # Standalone test: fetch a random article and prepare it for translation
    from src.orchestrator import fetch_random_wiki_article
    title, text = fetch_random_wiki_article()
    if title and text:
        processor = LinguaProcessor(target_lang_name="German", vocab_path="../data/vocabulary.md")
        result = processor.process_daily_content(text, title=title)
        print(f"\nInstruction for Agent:\n{result['instruction']}")
